package view;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtPolynomial = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbMethod = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtInterval1 = new javax.swing.JTextField();
        txtInterval2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPoint1 = new javax.swing.JTextField();
        txtPoint2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbStopType = new javax.swing.JComboBox();
        txtStopValue = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        btnGraph = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tpTable = new javax.swing.JTabbedPane();
        spTable = new javax.swing.JScrollPane(rfTable);
        spTable2 = new javax.swing.JScrollPane(secantTable);
        spTable3 = new javax.swing.JScrollPane(bisectionTable);
        spTable4 = new javax.swing.JScrollPane(newtonsTable);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Hobbit SF", 0, 14)); // NOI18N
        jLabel1.setText("Numerical Methods Simulation");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Identify the following:"));

        jLabel2.setText("Polynomial:");

        jLabel3.setText("Method:");

        cbMethod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Regula Falsi", "Secant", "Bisection", "Newton's" }));
        hideTextFields();

        jLabel4.setText("Interval:");

        jLabel5.setText("Points:");

        jLabel6.setText("Stop Value:");

        cbStopType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Iteration", "TOL" }));

        btnCalculate.setText("Calculate");

        btnGraph.setText("Show Graph");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGraph)
                    .addComponent(btnCalculate)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPolynomial)
                            .addComponent(cbMethod, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtInterval1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtInterval2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPoint1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbStopType, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtStopValue)
                                    .addComponent(txtPoint2))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbStopType, txtInterval1, txtInterval2, txtPoint1, txtPoint2, txtStopValue});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCalculate, btnGraph});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPolynomial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtInterval1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInterval2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPoint1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPoint2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbStopType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtStopValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCalculate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGraph)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Table Results:"));

        tpTable.addTab("Regula Falsi", spTable);
        tpTable.addTab("Secant Method", spTable2);
        tpTable.addTab("Bisection Method", spTable3);
        tpTable.addTab("Newton's Method", spTable4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpTable, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpTable, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Regula Falsi Table
    private String rfColNames[] = {"Iteration", "x0", "x1", "x2", "y0", "y1", "y2", "Error"};
    public DefaultTableModel rfTableModel = new DefaultTableModel(null, rfColNames);
    private JTable rfTable = new JTable(rfTableModel);

    public void rfAddRow(int iteration, double x0, double x1, double x2, double y0, double y1, double y2, double error) {
        this.rfTableModel.addRow(new Object[]{iteration, x0, x1, x2, y0, y1, y2, error});
    }
    //Secant Table
    private String secantColNames[] = {"Iteration", "x", "f(x)", "Error"};
    public DefaultTableModel secantTableModel = new DefaultTableModel(null, secantColNames);
    private JTable secantTable = new JTable(secantTableModel);

    public void secantAddRow(int iteration, double x, double y, double error) {
        this.secantTableModel.addRow(new Object[]{iteration, x, y, error});
    }

    private String bisectionColNames[] = {"Iteration", "x0", "x1", "x2", "y0", "y1", "y2", "Error"};
    public DefaultTableModel bisectionTableModel = new DefaultTableModel(null, bisectionColNames);
    private JTable bisectionTable = new JTable(bisectionTableModel);

    public void bisectionAddRow(int iteration, double x0, double x1, double x2, double y0, double y1, double y2, double error) {
        this.bisectionTableModel.addRow(new Object[]{iteration, x0, x1, x2, y0, y1, y2, error});
    }

    private String newtonsColNames[] = {"Iteration", "x", "f(x)", "Error"};
    public DefaultTableModel newtonsTableModel = new DefaultTableModel(null, newtonsColNames);
    private JTable newtonsTable = new JTable(newtonsTableModel);

    public void newtonsAddRow(int iteration, double x, double y, double error) {
        this.newtonsTableModel.addRow(new Object[]{iteration, x, y, error});
    }
    
    public void addCalculateBtnListener(ActionListener btn) {
        btnCalculate.addActionListener(btn);
    }

    public void addGraphBtnListener(ActionListener btn) {
        btnGraph.addActionListener(btn);
    }

    public void addMethodCbListener(ActionListener cb) {
        cbMethod.addActionListener(cb);
    }

    public String getCbMethod() {
        return cbMethod.getSelectedItem().toString();
    }

    public String getCbStopType() {
        return cbStopType.getSelectedItem().toString();
    }

    public double getTxtPoint1() {
        return Double.parseDouble(txtPoint1.getText());
    }

    public double getTxtPoint2() {
        return Double.parseDouble(txtPoint2.getText());
    }

    public double getTxtStopValue() {
        return Double.parseDouble(txtStopValue.getText());
    }

    public ArrayList<Double> getIntervals() {
        ArrayList<Double> intervals = new ArrayList<>();
        intervals.add(Double.parseDouble(txtInterval1.getText()));
        intervals.add(Double.parseDouble(txtInterval2.getText()));

        return intervals;
    }

    public ArrayList<Double> getPoints() {
        ArrayList<Double> points = new ArrayList<>();
        points.add(Double.parseDouble(txtPoint1.getText()));
        points.add(Double.parseDouble(txtPoint2.getText()));

        return points;
    }

    public ArrayList<Double> getTxtPolynomial() {
        ArrayList<Double> polynomial = new ArrayList<Double>();
        String[] temp = txtPolynomial.getText().split(" ");

        for (int i = 0; i < temp.length; i++) {
            polynomial.add(Double.parseDouble(temp[i]));
        }

        return polynomial;
    }

    public void hideTextFields() {
        if (cbMethod.getSelectedItem().equals("Regula Falsi") || (cbMethod.getSelectedItem().equals("Bisection"))) {
            txtPoint1.setEnabled(false);
            txtPoint2.setEnabled(false);

            txtInterval1.setEnabled(true);
            txtInterval2.setEnabled(true);
        } 
        else if (cbMethod.getSelectedItem().equals("Secant")){
            txtInterval1.setEnabled(false);
            txtInterval2.setEnabled(false);

            txtPoint1.setEnabled(true);
            txtPoint2.setEnabled(true);
        }
        else if (cbMethod.getSelectedItem().equals("Newton's")){
            txtInterval1.setEnabled(false);
            txtInterval2.setEnabled(false);

            txtPoint1.setEnabled(true);
            txtPoint2.setEnabled(false);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnGraph;
    private javax.swing.JComboBox cbMethod;
    private javax.swing.JComboBox cbStopType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane spTable;
    private javax.swing.JScrollPane spTable2;
    private javax.swing.JScrollPane spTable3;
    private javax.swing.JScrollPane spTable4;
    public javax.swing.JTabbedPane tpTable;
    private javax.swing.JTextField txtInterval1;
    private javax.swing.JTextField txtInterval2;
    private javax.swing.JTextField txtPoint1;
    private javax.swing.JTextField txtPoint2;
    private javax.swing.JTextField txtPolynomial;
    private javax.swing.JTextField txtStopValue;
    // End of variables declaration//GEN-END:variables
}
